# Generated by Django 4.1.7 on 2023-04-11 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('lead', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lead.lead'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_comments', to='team.team'),
        ),
    ]
